dist: xenial
jobs:
    include:
     - language:
           - python
           
        python: 3.6
    
        install:
          - "pip install -U mypy black"
          - "pip install pylint"
          -  "go get -u golang.org/x/lint/golint" 	  
     - deploy:
          provider: script
          script: task.sh
          on:
             branch:  main	 #hai
             
             
