dist: xenial
jobs:
    include:
     - language:
           - python
           - go
        python: 3.6
        go:
          - 1.11.x
          - 1.13.x
          - 1.14.x
        install:
          - "pip install -U mypy black"
          - "pip install pylint"
          -  "go get -u golang.org/x/lint/golint" 	  
     - deploy:
          provider: script
          script: task.sh
          on:
             branch:  main	 #hai
             
             
